name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Black (code formatting)
      run: |
        pip install black
        black --check .
    - name: Run Bandit (security scan)
      run: |
        pip install bandit
        bandit -r .
    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=app --cov-report=xml
    - name: Validate OpenAPI spec
      run: |
        pip install openapi-spec-validator
        curl http://localhost:5000/apispec.json -o apispec.json
        openapi-spec-validator apispec.json
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml

  load-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust
    - name: Run Locust load test
      run: |
        locust -f tests/locustfile.py --headless --users 50 --spawn-rate 10 --run-time 1m --host http://localhost:5000
      env:
        API_KEY: my-secure-api-key

  build-and-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t smarttextgen-api .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'smarttextgen-api'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
